# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9443f5d05f35fbd4388c0795ed47b934d68a817b0f3d7a5f596527b9aa47f27401bfa94894ffd4a8f6fd2a53278e3df5008c47d803709df43ec883537b81b57d

test:
  secret_key_base: 574d9afe790d23f47b5db5b67179a8f10cb5e9bf8edcb39ba812a9c7981de92e231e993571d336ee5254440caf40c92e596028b52cc9a143814ddbf8b015be30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
